// @generated - This file is generated by esquema-codegen (forked from atrium-codegen). DO NOT EDIT.
//!Definitions for the `place.stream.richtext.facet` namespace.
///Annotation of a sub-string within rich text.
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct MainData {
    pub features: Vec<atrium_api::types::Union<MainFeaturesItem>>,
    pub index: crate::app::bsky::richtext::facet::ByteSlice,
}
pub type Main = atrium_api::types::Object<MainData>;
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(tag = "$type")]
pub enum MainFeaturesItem {
    #[serde(rename = "app.bsky.richtext.facet#mention")]
    AppBskyRichtextFacetMention(Box<crate::app::bsky::richtext::facet::Mention>),
    #[serde(rename = "app.bsky.richtext.facet#link")]
    AppBskyRichtextFacetLink(Box<crate::app::bsky::richtext::facet::Link>),
}
