// @generated - This file is generated by esquema-codegen (forked from atrium-codegen). DO NOT EDIT.
//!Definitions for the `place.stream.chat` namespace.
pub mod defs;
pub mod gate;
pub mod message;
pub mod profile;
#[derive(Debug)]
pub struct Gate;
impl atrium_api::types::Collection for Gate {
    const NSID: &'static str = "place.stream.chat.gate";
    type Record = gate::Record;
}
#[derive(Debug)]
pub struct Message;
impl atrium_api::types::Collection for Message {
    const NSID: &'static str = "place.stream.chat.message";
    type Record = message::Record;
}
#[derive(Debug)]
pub struct Profile;
impl atrium_api::types::Collection for Profile {
    const NSID: &'static str = "place.stream.chat.profile";
    type Record = profile::Record;
}
