// @generated - This file is generated by esquema-codegen (forked from atrium-codegen). DO NOT EDIT.
//!Definitions for the `place.stream.defs` namespace.
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct BlockViewData {
    pub blocker: crate::app::bsky::actor::defs::ProfileViewBasic,
    pub cid: atrium_api::types::string::Cid,
    pub indexed_at: atrium_api::types::string::Datetime,
    pub record: crate::app::bsky::graph::block::Record,
    pub uri: String,
}
pub type BlockView = atrium_api::types::Object<BlockViewData>;
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct RenditionData {
    pub name: String,
}
pub type Rendition = atrium_api::types::Object<RenditionData>;
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct RenditionsData {
    pub renditions: Vec<Rendition>,
}
pub type Renditions = atrium_api::types::Object<RenditionsData>;
