// @generated - This file is generated by esquema-codegen (forked from atrium-codegen). DO NOT EDIT.
//!Definitions for the `place.stream.live` namespace.
pub mod get_live_users;
pub mod get_profile_card;
pub mod get_segments;
