// @generated - This file is generated by esquema-codegen (forked from atrium-codegen). DO NOT EDIT.
//!Definitions for the `place.stream.server` namespace.
pub mod create_webhook;
pub mod defs;
pub mod delete_webhook;
pub mod get_webhook;
pub mod list_webhooks;
pub mod settings;
pub mod update_webhook;
#[derive(Debug)]
pub struct Settings;
impl atrium_api::types::Collection for Settings {
    const NSID: &'static str = "place.stream.server.settings";
    type Record = settings::Record;
}
