// @generated - This file is generated by esquema-codegen (forked from atrium-codegen). DO NOT EDIT.
//!Definitions for the `place.stream` namespace.
pub mod chat;
pub mod defs;
pub mod graph;
pub mod key;
pub mod live;
pub mod livestream;
pub mod richtext;
pub mod segment;
pub mod server;
#[derive(Debug)]
pub struct Key;
impl atrium_api::types::Collection for Key {
    const NSID: &'static str = "place.stream.key";
    type Record = key::Record;
}
#[derive(Debug)]
pub struct Livestream;
impl atrium_api::types::Collection for Livestream {
    const NSID: &'static str = "place.stream.livestream";
    type Record = livestream::Record;
}
#[derive(Debug)]
pub struct Segment;
impl atrium_api::types::Collection for Segment {
    const NSID: &'static str = "place.stream.segment";
    type Record = segment::Record;
}
