// @generated - This file is generated by esquema-codegen (forked from atrium-codegen). DO NOT EDIT.
//!Definitions for the `place.stream.chat.defs` namespace.
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct MessageViewData {
    pub author: crate::app::bsky::actor::defs::ProfileViewBasic,
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub chat_profile: core::option::Option<crate::place::stream::chat::profile::Record>,
    pub cid: atrium_api::types::string::Cid,
    ///If true, this message has been deleted or labeled and should be cleared from the cache
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub deleted: core::option::Option<bool>,
    pub indexed_at: atrium_api::types::string::Datetime,
    pub record: atrium_api::types::Unknown,
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub reply_to: core::option::Option<atrium_api::types::Union<MessageViewReplyToRefs>>,
    pub uri: String,
}
pub type MessageView = atrium_api::types::Object<MessageViewData>;
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(tag = "$type")]
pub enum MessageViewReplyToRefs {
    #[serde(rename = "place.stream.chat.defs#messageView")]
    PlaceStreamChatDefsMessageView(Box<crate::place::stream::chat::defs::MessageView>),
}
